spring:
  application:
    name: online-store
  datasource:
    url: jdbc:postgresql://localhost:5432/online-store
    username: USERNAME
    password: PASSWORD
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
server:
  port: 3000