version: '3'
services:
  postgres: # POSTGRESQL DATABASE
    image: postgres:16.4
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 240M
    networks:
      - online-store
  pgadmin: # PGADMIN PSQL ADM
    image: dpage/pgadmin4:8.12.0
    container_name: pgadmin 
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - '3002:80'
    volumes:
      - pgadmin:/pgadmin4
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 240M
    networks:
      - online-store
  mongodb: # MONGODB
    image: mongo:8.0.1
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 240M
    networks:
      - online-store
  mongo-express: # MONGODB
    image: mongo-express:1.0.2-20
    container_name: mongo-express
    environment:
      ME_CONFIG_MONGODB_SERVER: ${MONGODB_SERVER}
      ME_CONFIG_MONGODB_PORT: ${MONGODB_PORT}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGODB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGODB_PASSWORD}
      ME_CONFIG_MONGODB_URL: ${MONGODB_URL}
      ME_CONFIG_BASICAUTH: false
    ports:
      - '3003:8081'
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 240M
    networks:
      - online-store

volumes:
  postgres:
  pgadmin:
  mongodb:
networks:
  online-store:
